# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Gabriel Souza
description: Técnico programador, trabalho com o desenvolvimento de sistemas desde 2018.
baseurl: ""
url: https://gabrielsouza.dev.br

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Gabriel Souza
  description:
    - Olá, sou Gabriel Souza.
    - Técnico programador desde 2018.
    - Trabalho com desenvolvimento de sistemas.
    - Minhas principais linguagens são JS/TS (Node.js) e PHP.
    - Saiba mais sobre mim no Linkedin.
    - Conheça alguns de meus projetos no link 'site de projetos'.
    - Visite também meu projeto de estudos, onde eu falo sobre tecnologia.
    - Você pode acessar através do link 'projeto de estudos' mais abaixo.
    - Obrigado por estar aqui!
  address:
    - Maringá, Paraná.
  contact:
    telefone: +55 44 9 91580952
    e-mail: gsdesenvolvedor@gmail.com
  profiles:
    site-de-projetos: https://gsdesenvolvedor.com.br
    projeto-de-estudos: https://codigoeconteudo.com.br
    meu-whatsapp: https://wa.me/+5544991580952
    meu-twitter: https://twitter.com/gsdesenvolvedor
    meu-instagram: https://www.instagram.com/gsdesenvolvedor
    meu-linkedin: https://www.linkedin.com/in/gsdesenvolvedor/
    meu-github: https://github.com/gsdesenvolvedor

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
