# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Gabriel Souza
description: Sou técnico programador formado em 2018 e trabalho com programação desde então.
baseurl: ""
url: https://gabrielsouza.dev.br

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  nome: Gabriel Souza
  descricao:
    - Sou técnico programador formado em 2018 e trabalho com programação desde então.
    - Meu histórico profissional pode ser encontrado no LinkedIn e em meu currículo que está em anexo.
    - Meus projetos independentes e de portfólio estão disponíveis em meu site de projetos.
    - Meu projeto hobbista atual é o desenvolvimento de um espaço que eu chamo de Código e Conteúdo.
  cv: assets/curriculo.pdf
  endereco:
    - Maringá, Paraná.
  contato:
    telefone: +55 44 9 91580952
    e-mail: gsdesenvolvedor@gmail.com
  meus-sites:
    site-de-projetos: https://gsdesenvolvedor.com.br
    projeto-hobbista: https://codigoeconteudo.com.br
  redes-socais:
    twitter: https://twitter.com/gsdesenvolvedor
    instagram: https://www.instagram.com/gsdesenvolvedor
    linkedin: https://www.linkedin.com/in/gsdesenvolvedor/
    github: https://github.com/gsdesenvolvedor

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
