# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Gabriel Souza
description: Técnico programador, trabalho com o desenvolvimento de sistemas desde 2018.
baseurl: ""
url: https://gabrielsouza.dev.br

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Gabriel Souza
  description:
    - Olá, sou Gabriel Souza.
    - Técnico programador desde 2018.
    - Trabalho com desenvolvimento de sistemas.
    - Minhas principais linguagens são JS/TS (Node.js) e PHP.
    - Saiba mais sobre mim no Linkedin e conheça meus projetos em 'projetos'.
    - Visite também o "código e conteúdo", onde eu falo sobre tecnologia.
    - Obrigado por estar aqui!
  address:
    - Maringá, Paraná.
  contact:
    e-mail: gsdesenvolvedor@gmail.com
  profiles:
    projetos: https://gsdesenvolvedor.com.br
    codigo-e-conteudo: https://codigoeconteudo.com.br
    twitter: https://twitter.com/gsdesenvolvedor
    instagram: https://www.instagram.com/gsdesenvolvedor
    linkedin: https://www.linkedin.com/in/gsdesenvolvedor/
    github: https://github.com/gsdesenvolvedor

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
