# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Gabriel Souza
description: Técnico programador, trabalhando com desenvolvimento de sistemas desde 2015.
baseurl: ""
url: https://gabrielsouza.dev.br

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Gabriel Souza
  description:
    - Sou técnico programador e trabalho com desenvolvimento de sistemas desde 2015.
    - Meu histórico profissional pode ser encontrado no currículo que está em anexo.
    - Meus projetos de portfólio estão disponíveis em meu site de projetos.
    - Meu projeto hobbista atual é o Código e Conteúdo (espaço de programação).
  cv: assets/curriculo.pdf
  address:
    - Maringá, Paraná.
  contact:
    telefone: +55 44 9 91580952
    e-mail: gsdesenvolvedor@gmail.com
  profiles:
    site-de-projetos: https://gsdesenvolvedor.com.br
    projeto-hobbista: https://codigoeconteudo.com.br
    meu-whatsapp: https://wa.me/+5544991580952
    meu-twitter: https://twitter.com/gsdesenvolvedor
    meu-instagram: https://www.instagram.com/gsdesenvolvedor
    meu-linkedin: https://www.linkedin.com/in/gsdesenvolvedor/
    meu-github: https://github.com/gsdesenvolvedor

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never
